KristianRosenvold: Revert "AlexeiBarantsev: Remove a temporary directory that contains a profile extracted from json string. FirefoxProfile(dir) constructor copies content of this directory (webdriver*) to a new profile  directory (anonymous*), so immediately after copying it can be safely removed. Fixes issue 1934"
Broke firefox tests, please let me know if you need any assistance in tracking this down.

Testcase: testUserPrefsArePreservedWhenConvertingToAndFromJson took 0.009 sec
	FAILED
expected:<http://www.example.com> but was:<about:blank>
junit.framework.AssertionFailedError: expected:<http://www.example.com> but was:<about:blank>
	at org.openqa.selenium.firefox.FirefoxProfileTest.testUserPrefsArePreservedWhenConvertingToAndFromJson(FirefoxProfileTest.java:230)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.extensions.TestSetup.run(TestSetup.java:27)

This reverts commit e1f01f528ec9ec1d43ccc493b40ea5535092d854.

r13956